version: 0.1
phases:
  install:
    commands:
      - npm install      
      - npm install -g serverless
  build:
    commands:
      - serverless deploy --stage develop
  post_build:
    commands:
      - echo 'build complete'