name: Upload CHANGELOG to S3

on:
  push:
    branches:
      - feature/cicd

jobs:
  zip-files:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: api/
          dest: api-source.zip
      - run: | 
          ls -a

      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::773103429818:role/PopulateS3FormGitRepo
          aws-region: ap-south-1
      - name: list files
        run: |
          ls -a
      - name: Copy files to the test website with the AWS CLI
        run: | 
          aws s3 sync . s3://cicd-source-demo-1 
  
